// Label Template Service using IndexedDB
// Persists to browser IndexedDB, falls back to localStorage if IDB not available

const DB_NAME = "achd_terminal_labels";
const DB_VERSION = 1;
const META_STORE = "meta";
const TEMPLATE_STORE = "templates";
const LS_KEY = "achd_label_templates_fallback";

// Open/initialize IndexedDB database
function openDB() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains(META_STORE)) {
        db.createObjectStore(META_STORE);
      }
      if (!db.objectStoreNames.contains(TEMPLATE_STORE)) {
        db.createObjectStore(TEMPLATE_STORE, { keyPath: "id", autoIncrement: true });
      }
    };
    request.onsuccess = (event) => resolve(event.target.result);
    request.onerror = (event) => reject(new Error("IndexedDB error"));
    request.onblocked = () => {/* handled */};
  });
}

// Save a label template
export async function saveTemplate(template) {
  try {
    const db = await openDB();
    const tx = db.transaction(TEMPLATE_STORE, "readwrite");
    const store = db.objectStore(TEMPLATE_STORE);
    // If template has no id, it will be auto-generated by autoIncrement
    const result = await store.add(template);
    await tx.done;
    return result; // auto-generated key
  } catch (e) {
    // Fallback to localStorage if IDB fails
    console.warn("IndexedDB failed, falling back to localStorage", e);
    const data = JSON.parse(localStorage.getItem(LS_KEY) || "[]");
    const existingIdx = data.findIndex((t) => t.id === template.id);
    if (template.id !== undefined && template.id !== null) {
      if (existingIdx >= 0) data[existingIdx] = template;
      else data.push(template);
    } else {
      data.push({ ...template, id: Date.now() });
    }
    localStorage.setItem(LS_KEY, JSON.stringify(data));
    return data.length - 1; // return index
  }
}

// Get all label templates
export async function getTemplates() {
  try {
    const db = await openDB();
    const tx = db.transaction(TEMPLATE_STORE, "readonly");
    const store = db.objectStore(TEMPLATE_STORE);
    const all = await store.getAll();
    await tx.done;
    return all;
  } catch (e) {
    return JSON.parse(localStorage.getItem(LS_KEY) || "[]");
  }
}

// Get a single template by id
export async function getTemplate(id) {
  try {
    const db = await openDB();
    const tx = db.transaction(TEMPLATE_STORE, "readonly");
    const store = db.objectStore(TEMPLATE_STORE);
    const record = await store.get(id);
    await tx.done;
    return record;
  } catch (e) {
    const data = JSON.parse(localStorage.getItem(LS_KEY) || "[]");
    return data.find((t) => t.id === id) || null;
  }
}

// Update a label template
export async function updateTemplate(id, template) {
  try {
    const db = await openDB();
    const tx = db.transaction(TEMPLATE_STORE, "readwrite");
    const store = db.objectStore(TEMPLATE_STORE);
    const record = { id, ...template };
    await store.put(record);
    await tx.done;
    return true;
  } catch (e) {
    // Fallback
    const data = JSON.parse(localStorage.getItem(LS_KEY) || "[]");
    const idx = data.findIndex((t) => t.id === id);
    if (idx >= 0) {
      data[idx] = { ...data[idx], ...template };
      localStorage.setItem(LS_KEY, JSON.stringify(data));
      return true;
    }
    return false;
  }
}

// Delete a label template
export async function deleteTemplate(id) {
  try {
    const db = await openDB();
    const tx = db.transaction(TEMPLATE_STORE, "readwrite");
    const store = db.objectStore(TEMPLATE_STORE);
    await store.delete(id);
    await tx.done;
    return true;
  } catch (e) {
    const data = JSON.parse(localStorage.getItem(LS_KEY) || "[]");
    const filtered = data.filter((t) => t.id !== id);
    localStorage.setItem(LS_KEY, JSON.stringify(filtered));
    return filtered.length !== data.length;
  }
}

// Set active template (store id in meta store)
export async function setActiveTemplate(templateId) {
  try {
    const db = await openDB();
    const tx = db.transaction([META_STORE, TEMPLATE_STORE], "readwrite");
    const metaStore = db.objectStore(META_STORE);
    await metaStore.put({ id: "activeTemplate", value: templateId }, "activeTemplate");
    await tx.done;
    return true;
  } catch (e) {
    // Fallback: just store in localStorage
    localStorage.setItem("achd_active_template", templateId || "");
    return true;
  }
}

// Get active template id
export async function getActiveTemplateId() {
  try {
    const db = await openDB();
    const tx = db.transaction(META_STORE, "readonly");
    const metaStore = db.objectStore(META_STORE);
    const meta = await metaStore.get("activeTemplate");
    await tx.done;
    return meta ? meta.value : null;
  } catch (e) {
    return localStorage.getItem("achd_active_template") || null;
  }
}

// Get active template full data
export async function getActiveTemplate() {
  const id = await getActiveTemplateId();
  if (!id) return null;
  return getTemplate(id);
}

// Helper types for the UI
export const TemplateType = {
  TEXTO: "texto",
  CAMPO: "campo",
  QR_CODE: "qrcode",
  CODIGO_BARRAS: "barcode",
  RANGE: "range",
  SERPENTINE: "serpentine"
};

// Default template dimensions in mm
export const DefaultDimensions = {
  largura: 50,
  altura: 25
};

// Template element schema
export function createDefaultElement(tipo, overrides = {}) {
  const base = {
    id: Date.now().toString() + Math.random().toString(36).substr(2),
    tipo,
    x: 0,
    y: 0,
    // default dimensions will be relative to label size
    fonteMm: 3,
    negrito: false,
    alinhamento: "esq",
    rotacao: "horizontal",
    caixaBorda: false,
    larguraFixa: false,
    alturaFixa: false,
    ...overrides
  };
  return base;
}